xun082/DocFlow

- .dockerignore
- Dockerfile
- package.json
- src/components/layout/TabSidebar/tabs/folder/ShareDialog.tsx
- src/components/ui/calendar.tsx
- src/components/ui/dialog.tsx
- src/components/ui/select.tsx
- src/hooks/useCollaborativeEditor.ts
- src/lib/utils.ts
> perf: ⚡️ 优化协同连接性能与 Docker 构建流程

- src/app/not-found.tsx
> feat: 🚀 新增404页面

- .github/workflows/deploy.yml
> ci: 🎡 优化自动化部署脚本

- src/app/auth/email/page.tsx
- src/app/dashboard/calendar/page.tsx
- src/app/dashboard/contacts/page.tsx
- src/app/dashboard/layout.tsx
- src/app/dashboard/meeting/page.tsx
- src/app/dashboard/messages/page.tsx
- src/app/dashboard/more/page.tsx
- src/app/dashboard/page.tsx
- src/app/dashboard/settings/page.tsx
- src/app/docs/layout.tsx
- src/app/page.tsx
- src/components/layout/Header/index.tsx
- src/middleware.ts
- src/styles/index.css
> feat: 🚀 新增控制台页面

- .github/workflows/deploy.yml
- .github/workflows/lint.yml
> ci: 🎡 为 ci 环境添加 npmrc 相关配置

- pnpm-workspace.yaml
- src/app/docs/_components/DocumentSidebar/BlocksTab.tsx
- src/app/docs/_components/DocumentSidebar/SearchTab.tsx
- src/app/docs/_components/DocumentSidebar/SettingsTab.tsx
- src/app/docs/_components/DocumentSidebar/TemplatesTab.tsx
- src/app/docs/_components/TableOfContents/index.tsx
- src/extensions/extension-kit-server.ts
- src/extensions/index.ts
- src/hooks/useCollaborativeEditor.ts
> fix: 🧩 删除 workspace 文件并解决服务端渲染的问题

- src/extensions/MarkdownPaste/MarkdownPaste.ts
支持 markdown 格式中图片的复制粘贴
- Related to #37
> feat: 🚀 支持 markdown 格式中图片的复制粘贴

- src/app/page.tsx
> fix: 🧩 优化首页类型错误

- src/app/docs/_components/document-service.ts
- src/extensions/CodeBlock/CodeBlockComponent.tsx
- src/extensions/CodeBlock/SelectOnlyCode.ts
- src/extensions/DraggableBlock/DraggableBlock.ts
- src/extensions/extension-kit-server.ts
> fix: 🧩 修复 addExtensions error

- src/app/docs/_components/DocumentClient.tsx
- src/app/docs/_components/DocumentHeader/index.tsx
- src/app/docs/_components/TableOfContents/index.tsx
- src/app/layout.tsx
- src/app/page.tsx
- src/extensions/extension-kit.ts
> style: 🎨 优化文件侧边栏和编辑器 tab 添加空格功能

- package.json
- pnpm-lock.yaml
- src/extensions/Audio/Audio.ts
- src/extensions/Audio/AudioComponent.tsx
- src/extensions/Audio/index.ts
- src/extensions/SlashCommand/groups.ts
- src/extensions/extension-kit.ts
- src/extensions/index.ts
实现音频播放器组件，支持通过URL插入音频文件并播放
添加Plyr依赖用于音频播放器UI
在SlashCommand中增加音频插入选项
- Closes #
- Related to #
1. 添加音频播放器扩展功能
2. 使用了plyr
> feat(audio): 添加音频播放器扩展功能

- src/app/docs/_components/DocumentSidebar/folder/components/FileTree.tsx
优化侧边栏文件树样式
- Closes #39 
- Related to #
> style: 🎨 优化侧边栏文件树样式

- src/extensions/SlashCommand/SlashCommand.ts
在退出SlashCommand时添加移除滚动监听事件的逻辑，防止内存泄漏
- Closes #
- Related to #
修复前
修复后
> fix(SlashCommand): 修复退出时未移除滚动监听事件的问题

- src/app/docs/[room]/page.tsx
将useEffect中的文档获取逻辑重构为独立函数fetchDocumentContent
在WebSocket连接成功时主动调用该函数以确保内容同步
- Closes #
- Related to #
1. 将首次进来的 请求数据放在 websocket 链接成功里面，解决flushSync 错误问题
> refactor(文档页面): 将文档内容获取逻辑提取为独立函数并在连接时调用

- src/extensions/CodeBlock/CodeBlock.ts
- Closes #31 
- Related to #
1. 解决了```js 不可以选择语言的问题
2. 在 code 的最后面 按两次回车退出 code
> feat(CodeBlock): 添加双击Enter退出代码块功能

- src/app/docs/[room]/page.tsx
实现侧边栏的折叠展开功能，包括添加折叠按钮和宽度控制逻辑
引入侧边栏宽度常量定义，优化用户界面交互体验
1. 给文档大纲增加有关闭和打开按钮
- Closes #
- Related to #
> feat(侧边栏): 添加可折叠侧边栏功能

- src/extensions/ExcalidrawImage/ExcalidrawEditor.tsx
- src/extensions/ExcalidrawImage/ExcalidrawImage.tsx
- src/extensions/SlashCommand/SlashCommand.ts
- src/extensions/SlashCommand/groups.ts
将Excalidraw功能从外部链接改为内置编辑器实现
移除旧的SVG渲染方式，新增ExcalidrawEditor组件
优化SlashCommand的销毁逻辑
- Closes #
- Related to #
1. 修复了 popup 滚动的监听没有销毁
2. 增加了excalidraw，在文档中
> feat(Excalidraw): 增加了excalidraw 编辑器

- .env.development
- src/app/docs/[room]/page.tsx
- src/app/docs/_components/DocumentHeader/index.tsx
- src/services/document/index.ts
> fix: 🧩 修复协同连接数据不同步问题

- src/app/docs/layout.tsx
在文档布局组件中添加 'use client' 指令以支持客户端渲染
使用 useEffect 在组件挂载时初始化侧边栏状态
1. 修复编辑器中关闭侧边栏导致 doc 下侧边栏不显示的问题
- Closes #
- Related to #
> feat(文档布局): 添加客户端渲染支持并初始化侧边栏状态

- src/app/docs/[room]/page.tsx
- src/extensions/ImageUpload/view/ImageUpload.tsx
1. 修复图片上传后图片不显示
2. 修复 menu 和 手柄 随着页面滚动而滚动
- Closes #
- Related to #
前
——————
后
> fix(editor): 修复图片上传后删除范围错误并调整编辑器容器样式

- src/app/docs/_components/DocumentSidebar/folder/ShareDialog.tsx
- src/app/docs/_components/DocumentSidebar/folder/components/SharedDocuments.tsx
- src/services/document/index.ts
- src/services/document/type.ts
- src/styles/index.css
- Closes #
- Related to #
1. 修复了分享接口 code 为 201 的问题
2. 修复了同步用户名字会分割文本问题
3. 修复了分享文档不显示的问题
> fix(文档共享): 修复共享文档接口响应结构和状态码问题

- src/extensions/DragHandler/DragHandler.ts
添加 AudioBlockStrategy 类以支持音频类型的块内容创建
- Closes #
- Related to #
1. 增加拖拽音频到画布
> feat(DragHandler): 添加音频块策略支持

- src/app/docs/[room]/page.tsx
- Closes #
- Related to #
1. 删除多余的侧边栏目录
> refactor: 移除未使用的侧边栏和大纲相关代码

- src/app/docs/_components/DocumentSidebar/BlocksTab.tsx
- src/extensions/AI/AI.ts
- src/extensions/AI/AIComponent.tsx
- src/extensions/AI/index.ts
- src/extensions/DragHandler/DragHandler.ts
- src/extensions/SlashCommand/groups.ts
- src/extensions/extension-kit.ts
- src/extensions/index.ts
- src/utils/utils/isCustomNodeSelected.ts
- 创建AI扩展模块，支持在编辑器中插入AI交互块
- 实现AI组件React视图，包含提示输入和响应显示
- 添加侧边栏区块、斜杠命令和拖拽处理支持
- 配置AI模型参数和加载状态管理
- Closes #
- Related to #
1. 增加了ai扩展，可以使用/ai 来使用， 可以使用拖拽模块使用
2. 阻止ai扩展被选中后textMenu弹窗
> feat(AI): 添加AI组件支持，包括编辑器集成和交互界面

- package.json
- pnpm-lock.yaml
- src/app/auth/callback/page.tsx
- src/app/dashboard/knowledge/page.tsx
- src/components/ui/card.tsx
- src/utils/constants/navigation.tsx
> feat: 🚀 新增知识库页面并修复github 登录失败

- src/app/dashboard/knowledge/_components/KnowledgeCard.tsx
- src/app/dashboard/knowledge/page.tsx
- src/app/dashboard/knowledge/types.ts
- src/components/ui/alert.tsx
- src/services/knowledge/index.ts
- src/services/knowledge/types.ts
> feat: 🚀 新增知识库上传功能

- .env.development
- .env.production
- src/app/dashboard/page.tsx
- src/components/dashboard/DashboardHeader.tsx
- src/hooks/ws/useNotificationSocket.ts
- src/types/ws.ts
> feat: 🚀 新增 ws 并实现在线人数统计

- src/app/docs/_components/DocumentSidebar/folder/components/FileTree.tsx
- src/app/docs/_components/DocumentSidebar/folder/components/LoadingSkeleton.tsx
- src/app/docs/_components/DocumentSidebar/folder/components/RenderFile.tsx
- src/app/docs/_components/DocumentSidebar/folder/index.tsx
- src/stores/fileStore.ts
> fix: 🧩 修复文件空白情况下一直是骨架屏的问题

- src/app/dashboard/knowledge/_components/CreateKnowledgeDialog.tsx
- src/app/dashboard/knowledge/_components/KnowledgeCard.tsx
- src/app/dashboard/knowledge/_components/KnowledgeList.tsx
- src/extensions/AI/AIComponent.tsx
- src/utils/localstorage.ts
> fix: 🧩 修复知识库已知bug

- src/extensions/AI/AIComponent.tsx
- src/extensions/AI/components/AIInputPanel.tsx
- src/extensions/AI/hooks/useQuestion.ts
- src/extensions/AI/hooks/useSSEStream.ts
1. 优化ai 输入框回车触发请求， 
2. 修复ai 请求错误后将错误数据回显在文档中
- Closes #
- Related to #
> fix：优化ai 输入框回车触发请求， 修复ai 请求错误后将错误数据回显在文档中

- package.json
- pnpm-lock.yaml
- src/app/dashboard/podcast/page.tsx
- src/services/podcast/index.ts
- src/utils/constants/navigation.tsx
- Closes #
- Related to #
1. 增加了上传文件转博客的功能
> feat(播客): 添加播客管理功能

- src/app/dashboard/podcast/_components/PodcastList.tsx
- src/app/dashboard/podcast/_components/PodcastTaskList.tsx
- src/app/dashboard/podcast/_components/UploadResumeCard.tsx
- src/app/dashboard/podcast/page.tsx
- 新增UploadResumeCard组件，支持简历文件上传并处理上传成功后的逻辑。
- 添加PodcastTaskList组件，展示上传任务的状态和进度。
- 优化PodcastList组件，增加空状态处理，提升用户体验。
- 移除冗余代码，简化文件上传逻辑，增强可维护性。
- Closes #
- Related to #
> style(podcast): 重构播客页面，添加上传简历功能和任务列表组件

- src/app/dashboard/podcast/_components/PodcastList.tsx
- src/app/dashboard/podcast/_components/UploadResumeCard.tsx
- src/app/dashboard/podcast/page.tsx
- src/services/podcast/index.ts
- src/services/podcast/type.ts
- src/utils/localstorage.ts
> style: 🎨 优化 ai播客 页面

- src/app/dashboard/podcast/_components/PodcastList.tsx
- src/app/dashboard/podcast/_components/PodcastTaskList.tsx
- src/app/dashboard/podcast/page.tsx
- src/hooks/ws/useNotificationSocket.ts
- 在PodcastPage中添加useEffect以监听播客任务的完成状态，并在任务完成后延迟3秒刷新播客列表。
- 新增clearCompletedTasks函数以清理已完成的任务。
- 更新PodcastList组件以支持单个播客的展开/收起功能，优化用户体验。
- 在PodcastTaskList中为已完成的任务添加视觉反馈。
- Closes #
- Related to #
> feat(podcast): 添加播客任务完成状态监听与清理功能

- src/app/dashboard/layout.tsx
- src/app/dashboard/page.tsx
- src/components/dashboard/DashboardHeader.tsx
实现移动端侧边栏的响应式设计，添加遮罩层和关闭按钮，并优化导航菜单的点击行为。同时简化了头部组件，移除了WebSocket相关功能。
- Closes #
- Related to #
> feat(dashboard): 优化移动端侧边栏交互

- src/app/dashboard/podcast/_components/PodcastPageContent.tsx
- src/app/dashboard/podcast/page.tsx
> fix: 🧩 修复因为 useSearchParams 构建报错的问题

- src/app/docs/[room]/page.tsx
- src/app/docs/_components/DocumentHeader/index.tsx
> feat: 🚀 添加文档标题功能和优化文档头部显示

- src/styles/index.css
- src/styles/partials/collab.css
> style: 🎨 更新协作光标和菜单样式，确保层级关系正确

- src/styles/index.css
- src/styles/partials/collab.css
- src/styles/partials/table.css
> style: 🎨 强化协作光标和表格样式，提升层级管理和可见性

- src/extensions/AI/AIComponent.tsx
- src/extensions/AI/hooks/useSSEStream.ts
- src/extensions/AI/hooks/useTextExtraction.ts
> style: 🎨 增加响应内容引用和自动滚动功能，优化内容生成体验

- src/services/document/index.ts
增加获取所有文档的cacheTime参数，取消强缓存，修复重命名之后无法更新的错误
- [x ] 🐛 Bug 修复
- Closes #
- Related to #
- [x ] 我的代码符合项目的代码风格
- [ x] 我已经审核了自己的代码
- [ x] 我已经为复杂的代码部分添加了注释
- [ x] 我已经更新了相关文档
- [ x] 我的变更不会产生新的警告或错误
- [ x] 我已确认所有依赖项都已正确更新
> fix: 🧩 修复获取所有文档的缓存错误，解决重命名文档之后仍是旧数据的问题

- package.json
- pnpm-lock.yaml
- src/extensions/TableImage/components/TableImageView.tsx
为表格图片组件集成 react-photo-view 库，支持点击图片放大查看
1. 给表格的图片增加了全屏预览效果
- Closes #
- Related to #
1. 使用react-photo-view 来实现图片的全屏预览
> feat(TableImage): 添加图片查看器功能支持
